// Companies excluded everywhere: IT-services / consulting / staffing body shops
// that flood (especially Indian) software-engineer search results.
// Matched case-insensitively against a job's company name.

const PATTERNS = [
  // Indian IT services majors
  /infosys/i,
  /tata consultancy|\btcs\b/i,
  /wipro/i,
  /\bhcl\b|hcltech/i,
  /tech\s*mahindra/i,
  /ltimindtree|mindtree|\blti\b|l&t\s*infotech|larsen\s*&\s*toubro/i,
  /mphasis/i,
  /coforge/i,
  /birlasoft/i,
  /hexaware/i,
  /cyient/i,
  /zensar/i,
  /persistent\s*systems/i,
  /happiest\s*minds/i,
  /sonata\s*software/i,
  /\bkpit\b/i,
  /tata\s*elxsi|tata\s*technologies|tata\s*digital/i,
  /\binfotech\b/i,
  // Global consulting / services
  /deloitte/i,
  /accenture/i,
  /capgemini/i,
  /cognizant/i,
  /\bpwc\b|pricewaterhouse/i,
  /ernst\s*&\s*young|\bey\b/i,
  /\bkpmg\b/i,
  /\bdxc\b/i,
  /ntt\s*data/i,
  /\batos\b/i,
  /sopra\s*steria/i,
  /genpact/i,
  /\bwns\b/i,
  /sutherland/i,
  /virtusa/i,
  /\bust\b|ust\s*global/i,
  /nagarro/i,
  /quest\s*global/i,
  /globallogic/i,
  /\bencora\b|\bmovate\b|\bmovate\b/i,
  /concentrix|teleperformance|conduent|firstsource|eclerx|hinduja\s*global/i,
  /mckinsey/i,
  /boston\s*consulting|\bbcg\b/i,
  /bain\s*&\s*company/i,
  // Staffing / recruiting agencies common on LinkedIn (India + global)
  /diverse\s*lynx/i,
  /collabera/i,
  /teksystems/i,
  /randstad/i,
  /adecco/i,
  /manpower/i,
  /insight\s*global/i,
  /robert\s*half/i,
  /michael\s*page/i,
  /\bhays\b/i,
  /\bphoton\b/i,
  /mastech/i,
  /apex\s*systems/i,
  /mindlance/i,
  /talentburst/i,
  /compunnel/i,
  /synechron/i,
  /iris\s*software/i,
  /xoriant/i,
  /\bkforce\b/i,
  /experis/i,
  /judge\s*group/i,
  /pyramid\s*consulting/i,
  /net2source/i,
  /nityo/i,
  /russell\s*tobin/i,
  /\bdexian\b/i,
  /trigyn/i,
  /\bstaffing\b/i,
  /consultancy\s*services/i,
];

export function isBlockedCompany(name = "") {
  const n = String(name).trim();
  if (!n) return false;
  return PATTERNS.some((re) => re.test(n));
}
